id = "hledger-zed"
name = "hledger"
version = "0.0.1"
schema_version = 1
authors = ["Patrick Timoney <hleger-lsp@patrickt.co>"]
description = "Language Server Protocol support for the hledger plain text accounting tool"
repository = "https://github.com/ptimoney/hledger-zed"

[grammars.hledger]
repository = "file:///home/patrick/Development/hledger-lsp-group/tree-sitter-hledger"
rev = "510f8242efccbec0557373bc8bb1ebe3b74115af"

[language_servers.hledger-lsp]
name = "hledger Language Server"
languages = ["hledger"]
