id = "hledger-zed"
name = "hledger"
version = "0.0.1"
schema_version = 1
authors = ["Patrick Timoney <hleger-lsp@patrickt.co>"]
description = "Language Server Protocol support for the hledger plain text accounting tool"
repository = "https://github.com/ptimoney/hledger-zed"

[grammars.hledger]
repository = "https://github.com/ptimoney/tree-sitter-hledger"
rev = "3f68c44f86c5668a431c64f4af3375a9f4699fd5"

[language_servers.hledger-lsp]
name = "hledger Language Server"
languages = ["hledger"]
